apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messager
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - minio-secret.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - minio.yaml
  - s3-csi-secret.yaml
  - s3-csi-pv.yaml
  - s3-csi-pvc.yaml
  - users-migrations-cm.yaml
  - messages-migrations-cm.yaml
  - migrate-users-job.yaml
  - migrate-messages-job.yaml
  - user-service.yaml
  - message-service.yaml
  - bff.yaml
  - frontend.yaml
  - ingress.yaml