apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  POSTGRES_USER: messenger
  POSTGRES_PASSWORD: secret
  POSTGRES_DB_USERS: users_db
  POSTGRES_DB_MESSAGES: messages_db